spacer:
  locations:
  - name: documents
    current_path_regex: .*/[Dd]ocuments/.*
    current_path_command: pwd | sed 's:[Dd]ocuments/:[docs]:'
  - name: uppercase-all
    current_path_command: |
      pwd |  tr '[:lower:]' '[:upper:]'
  layouts:
    - name: here
      location_name: uppercase-all
      command: echo "I'm here"
      children:
        - location_name: uppercase-all
          direction: down

